async_mode: threaded
cache:
  base_dir: cache
  type: file
chunks:
  group_by_columns:
  - id
  overlap: 64
  size: 512
claim_extraction:
  description: Any claims or facts that could be relevant to information discovery.
  max_gleanings: 0
  prompt: prompts/claim_extraction.txt
cluster_graph:
  max_cluster_size: 10
community_report:
  max_input_length: 8000
  max_length: 2000
  prompt: prompts/community_report.txt
embed_graph:
  enabled: false
embeddings:
  async_mode: threaded
  llm:
    api_base: http://localhost:11434/v1
    api_key: ${GRAPHRAG_API_KEY}
    model: nomic-embed-text:latest
    provider: openai
    type: openai_embedding
encoding_model: cl100k_base
entity_extraction:
  entity_types:
  - organization
  - person
  - geo
  - event
  max_gleanings: 0
  prompt: prompts/entity_extraction.txt
global_search:
  concurrency: 32
input:
  base_dir: input
  file_encoding: utf-8
  file_pattern: .*\.txt$
  file_type: text
  type: file
llm:
  api_base: http://localhost:11434/v1
  api_key: ${GRAPHRAG_API_KEY}
  max_tokens: 1024
  model: sciphi/triplex:latest
  model_supports_json: true
  provider: ollama
  temperature: 0.5
  type: openai
local_search: null
parallelization:
  num_threads: 50
  stagger: 0.3
reporting:
  base_dir: output/${timestamp}/reports
  type: file
skip_workflows: []
snapshots:
  graphml: true
  raw_entities: true
  top_level_nodes: true
storage:
  base_dir: output/${timestamp}/artifacts
  type: file
summarize_descriptions:
  max_length: 500
  prompt: prompts/summarize_descriptions.txt
umap:
  enabled: false
